"""Generated by scripts/generate-python-views.py from schemas/protocol.schema.json; SHA-256 0524bce8cafa4d79a54c06f249090cf30577ee57a5df9aac905e4e13eadb2de3. Do not edit.

Read-only views of the SDK's results, for editors and type checkers (SPEC-0033 Y01). At run time
every result is a Snapshot; a view only describes it. Raw JSON keeps the wire's names.
"""
from __future__ import annotations

from collections.abc import Iterator, Mapping, Sequence
from typing import Any, Literal, Protocol


class View(Protocol):
    """What every view offers: read-only mapping access, as a Snapshot."""
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> Any: ...
    def as_dict(self) -> dict[str, Any]: ...


class ReceiptView(View, Protocol):
    """What the SDK adds to the result of a mutation, for a retry or a lookup."""
    @property
    def method(self) -> str:
        ...
    @property
    def scope(self) -> str | None:
        ...
    @property
    def idempotency_key(self) -> str:
        ...
    @property
    def retry_identity(self) -> RetryIdentityView:
        ...


class ApprovalRequestTargetView(View, Protocol):
    @property
    def task_id(self) -> str:
        ...
    @property
    def task_revision(self) -> int:
        ...
    @property
    def artifact_refs(self) -> Sequence[str]:
        ...
    @property
    def session_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def generation(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def dispatch_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def provider_session_id(self) -> str | None:
        "Absent when not set; use get()."
        ...
    @property
    def provider_turn_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def request_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def tool_name(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def permission(self) -> Any:
        "Absent when not set; use get()."
        ...
    @property
    def request_digest(self) -> str:
        "Absent when not set; use get()."
        ...


class ApprovalRequestView(View, Protocol):
    @property
    def approval_id(self) -> str:
        ...
    @property
    def task_id(self) -> str:
        ...
    @property
    def purpose(self) -> Literal["task_acceptance", "runtime_permission"]:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def status(self) -> Literal["pending", "approved", "denied", "revised", "expired", "invalidated"]:
        ...
    @property
    def target(self) -> ApprovalRequestTargetView:
        ...
    @property
    def summary(self) -> str:
        ...
    @property
    def evidence_refs(self) -> Sequence[str]:
        ...
    @property
    def expires_at(self) -> str:
        ...
    @property
    def comment(self) -> str:
        "Absent when not set; use get()."
        ...


class ContextPlanView(View, Protocol):
    @property
    def requested_mode(self) -> Literal["continue", "parallel_tools", "reuse", "fork", "fresh"]:
        ...
    @property
    def independent(self) -> bool:
        ...
    @property
    def dependency_task_ids(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def context_refs(self) -> Sequence[Mapping[str, Any]]:
        "Absent when not set; use get()."
        ...
    @property
    def candidate_session_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def snapshot_ref(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def fallback_modes(self) -> Sequence[Literal["continue", "parallel_tools", "reuse", "fork", "fresh"]]:
        "Absent when not set; use get()."
        ...
    @property
    def max_queue_wait_ms(self) -> int:
        "Absent when not set; use get()."
        ...


class DispatchBudgetView(View, Protocol):
    @property
    def policy_version(self) -> Literal[2]:
        ...
    @property
    def entered_at(self) -> str:
        ...
    @property
    def acceptance_deadline_at(self) -> str:
        ...
    @property
    def deadline_at(self) -> str:
        ...
    @property
    def effective_acceptance_ms(self) -> int:
        ...
    @property
    def effective_turn_ms(self) -> int:
        ...
    @property
    def acceptance_source(self) -> str:
        ...
    @property
    def turn_source(self) -> str:
        ...


class ExecutionConflictResolutionView(View, Protocol):
    @property
    def operation_id(self) -> str:
        ...
    @property
    def evidence_ref(self) -> str:
        ...
    @property
    def occurred_at(self) -> str:
        ...


class ExecutionConflictView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def dispatch_id(self) -> str:
        ...
    @property
    def session_id(self) -> str:
        ...
    @property
    def task_id(self) -> str:
        ...
    @property
    def generation(self) -> int:
        ...
    @property
    def status(self) -> Literal["open", "resolved"]:
        ...
    @property
    def release_evidence_ref(self) -> str | None:
        ...
    @property
    def conflicting_evidence_ref(self) -> str:
        ...
    @property
    def created_at(self) -> str:
        ...
    @property
    def resolution(self) -> ExecutionConflictResolutionView:
        "Absent when not set; use get()."
        ...


class ExecutionLeaseView(View, Protocol):
    @property
    def version(self) -> Literal[1]:
        ...
    @property
    def status(self) -> Literal["held", "released"]:
        ...
    @property
    def acquired_at(self) -> str:
        ...
    @property
    def released_at(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def release_reason(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def release_evidence_ref(self) -> str:
        "Absent when not set; use get()."
        ...


class HandoffListResultView(View, Protocol):
    @property
    def handoffs(self) -> Sequence[HandoffRequestView]:
        ...
    @property
    def next_cursor(self) -> str | None:
        ...


class HandoffRequestView(View, Protocol):
    @property
    def handoff_id(self) -> str:
        ...
    @property
    def status(self) -> Literal["pending", "accepted", "rejected", "expired", "invalidated"]:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def from_task_id(self) -> str:
        ...
    @property
    def from_session_id(self) -> str:
        ...
    @property
    def from_dispatch_id(self) -> str:
        ...
    @property
    def from_generation(self) -> int:
        ...
    @property
    def root_task_id(self) -> str:
        ...
    @property
    def target_session_id(self) -> str:
        ...
    @property
    def goal(self) -> str:
        ...
    @property
    def context_refs(self) -> Sequence[Mapping[str, Any]]:
        ...
    @property
    def created_at(self) -> str:
        ...
    @property
    def expires_at(self) -> str:
        ...
    @property
    def resolved_at(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def task_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def comment(self) -> str:
        "Absent when not set; use get()."
        ...


class InitializeResultCapabilitiesStoreNamespacesView(View, Protocol):
    @property
    def version(self) -> Literal[1]:
        ...
    @property
    def expected_store_id(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def digest_version(self) -> Literal[1]:
        "Absent when not set; use get()."
        ...


class InitializeResultCapabilitiesView(View, Protocol):
    @property
    def store_namespaces(self) -> InitializeResultCapabilitiesStoreNamespacesView:
        ...
    @property
    def workflow(self) -> WorkflowCapabilityView:
        "Absent when not set; use get()."
        ...
    @property
    def readOnly(self) -> Mapping[str, Any]:
        "A host that answers reads from a store opened read-only (SPEC-0027 R09). Absent when not set; use get()."
        ...


class InitializeResultView(View, Protocol):
    @property
    def protocol_version(self) -> Literal["2.0"]:
        ...
    @property
    def engine_version(self) -> str:
        ...
    @property
    def schema_version(self) -> Literal[3]:
        ...
    @property
    def instance_id(self) -> str:
        ...
    @property
    def store_id(self) -> str:
        ...
    @property
    def capabilities(self) -> InitializeResultCapabilitiesView:
        ...


class MessageSnapshotView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def from_session_id(self) -> str:
        ...
    @property
    def idempotency_key(self) -> str:
        ...
    @property
    def status(self) -> Literal["persisted", "dispatching", "runtime_accepted", "completed", "failed", "outcome_unknown", "expired"]:
        ...
    @property
    def task_id(self) -> str:
        ...
    @property
    def to_session_id(self) -> str:
        ...
    @property
    def expected_generation(self) -> int:
        ...
    @property
    def kind(self) -> Literal["assignment", "finding", "result", "question"]:
        ...
    @property
    def summary(self) -> str:
        ...
    @property
    def artifact_refs(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def ttl_ms(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def reply_to_message_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def retry_identity(self) -> RetryIdentityView:
        "Absent when not set; use get()."
        ...
    @property
    def created_at(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def expires_at(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def hop_count(self) -> int:
        "Absent when not set; use get()."
        ...


class MoneyBudgetView(View, Protocol):
    @property
    def currency(self) -> str:
        ...
    @property
    def max_cost(self) -> str:
        ...
    @property
    def reserve_per_dispatch(self) -> str:
        ...


class OperationLifecycleView(View, Protocol):
    @property
    def entered_at(self) -> str:
        ...
    @property
    def deadline_at(self) -> str:
        ...
    @property
    def policy_version(self) -> Literal[1]:
        ...
    @property
    def kind(self) -> Literal["drain", "interrupt", "reconcile", "shutdown"]:
        ...
    @property
    def expected_generation(self) -> int | None:
        ...
    @property
    def expected_dispatch_id(self) -> str | None:
        ...
    @property
    def may_have_been_sent(self) -> bool:
        ...
    @property
    def last_evidence(self) -> str:
        ...
    @property
    def expired_at(self) -> str:
        "Absent when not set; use get()."
        ...


class OperationSnapshotErrorView(View, Protocol):
    @property
    def code(self) -> str:
        ...
    @property
    def message(self) -> str:
        ...


class OperationSnapshotResolutionView(View, Protocol):
    @property
    def operation_id(self) -> str:
        ...
    @property
    def outcome(self) -> str:
        ...
    @property
    def occurred_at(self) -> str:
        ...


class OperationSnapshotView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def method(self) -> str:
        ...
    @property
    def scope(self) -> str:
        ...
    @property
    def idempotency_key(self) -> str:
        ...
    @property
    def status(self) -> Literal["persisted", "completed", "noop", "rejected", "failed", "outcome_unknown"]:
        ...
    @property
    def target_id(self) -> str:
        ...
    @property
    def result(self) -> Any:
        "Method-specific raw JSON with original camelCase keys. sessions.reconcile may report executionReleased, resolved, unobservedResourcesReconciled and resourceCleanup. A pending cleanup requires the owner to retry reconcile with the original target, evidence and key; reading or waiting on this operation does not execute cleanup."
        ...
    @property
    def error(self) -> None | OperationSnapshotErrorView:
        ...
    @property
    def lifecycle(self) -> OperationLifecycleView:
        "Absent when not set; use get()."
        ...
    @property
    def resolution(self) -> OperationSnapshotResolutionView:
        "Absent when not set; use get()."
        ...
    @property
    def retry_identity(self) -> RetryIdentityView:
        "Absent when not set; use get()."
        ...


class RegisteredVerificationRuleView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def version(self) -> str:
        ...
    @property
    def argv(self) -> Sequence[str]:
        ...
    @property
    def cwd_relative(self) -> str:
        ...
    @property
    def timeout_ms(self) -> int:
        ...
    @property
    def permission_profile(self) -> Literal["read-only", "workspace-write"]:
        ...
    @property
    def success(self) -> Mapping[str, Any]:
        ...
    @property
    def max_output_bytes(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def baseline_paths(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def digest(self) -> str:
        ...
    @property
    def source(self) -> Literal["config", "runtime"]:
        ...
    @property
    def retired_at(self) -> str:
        "Set on a retired rule, which rules.list returns only with includeRetired (SPEC-0028 U04). Absent when not set; use get()."
        ...


class RetryIdentityView(View, Protocol):
    @property
    def store_id(self) -> str:
        ...
    @property
    def method(self) -> str:
        ...
    @property
    def scope(self) -> str:
        ...
    @property
    def idempotency_key(self) -> str:
        ...
    @property
    def digest_version(self) -> Literal[1]:
        ...
    @property
    def request_digest(self) -> str:
        ...


class RoutingDecisionView(View, Protocol):
    @property
    def policy_version(self) -> Literal[1]:
        ...
    @property
    def mode(self) -> Literal["continue", "parallel_tools", "reuse", "fork", "fresh"]:
        ...
    @property
    def candidate_session_id(self) -> str:
        ...
    @property
    def expected_generation(self) -> int:
        ...
    @property
    def enqueued_at(self) -> str:
        ...
    @property
    def deadline_at(self) -> str:
        ...
    @property
    def max_queue_wait_ms(self) -> int:
        ...
    @property
    def fallback_modes(self) -> Sequence[Literal["continue", "parallel_tools", "reuse", "fork", "fresh"]]:
        ...
    @property
    def reason_code(self) -> str:
        ...
    @property
    def submitted_at(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def expired_at(self) -> str:
        "Absent when not set; use get()."
        ...


class RuleListResultView(View, Protocol):
    @property
    def rules(self) -> Sequence[RegisteredVerificationRuleView]:
        ...


class RuntimeInspectionView(View, Protocol):
    @property
    def status(self) -> Literal["found", "not_found", "unavailable", "mismatch"]:
        ...
    @property
    def execution(self) -> Literal["unknown"]:
        ...
    @property
    def provider_session_id(self) -> str | None:
        ...
    @property
    def records(self) -> Sequence[Any]:
        ...
    @property
    def detail(self) -> str:
        ...
    @property
    def target(self) -> Any:
        "Absent when not set; use get()."
        ...
    @property
    def truncated(self) -> bool:
        ...


class RuntimeSpecView(View, Protocol):
    @property
    def provider(self) -> str:
        ...
    @property
    def model(self) -> str:
        ...


class SchedulerSnapshotConflictsView(View, Protocol):
    @property
    def conflict_id(self) -> str:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def dispatch_id(self) -> str:
        ...


class SchedulerSnapshotOccupantsView(View, Protocol):
    @property
    def task_id(self) -> str:
        ...
    @property
    def session_id(self) -> str:
        ...
    @property
    def dispatch_id(self) -> str:
        ...
    @property
    def lease_status(self) -> Literal["held", "released"]:
        ...
    @property
    def quarantined(self) -> bool:
        ...
    @property
    def last_evidence(self) -> str:
        ...
    @property
    def entered_at(self) -> str:
        ...


class SchedulerSnapshotView(View, Protocol):
    @property
    def max_active_sessions(self) -> int:
        ...
    @property
    def max_quarantined_dispatches(self) -> int:
        ...
    @property
    def execution_occupied(self) -> int:
        ...
    @property
    def quarantined(self) -> int:
        ...
    @property
    def quarantine_reserved(self) -> int:
        ...
    @property
    def can_dispatch(self) -> bool:
        ...
    @property
    def reasons(self) -> Sequence[str]:
        "Current reasons include EXECUTION_CAPACITY_EXHAUSTED, QUARANTINE_CAPACITY_EXCEEDED, HOST_STOPPING, SCHEDULER_FAILED (with HOST_STOPPING, after an internal failure stopped the host), RESOURCE_CLEANUP_PENDING and EXECUTION_EVIDENCE_CONFLICT. Clients must tolerate additional reason strings. Counts come from persisted dispatches; reasons also reflect this host's shutdown and in-memory cleanup state."
        ...
    @property
    def occupants(self) -> Sequence[SchedulerSnapshotOccupantsView]:
        ...
    @property
    def truncated(self) -> bool:
        ...
    @property
    def open_conflicts(self) -> int:
        ...
    @property
    def conflicts(self) -> Sequence[SchedulerSnapshotConflictsView]:
        ...
    @property
    def conflicts_truncated(self) -> bool:
        ...


class SessionExecutionView(View, Protocol):
    @property
    def dispatch_id(self) -> str:
        ...
    @property
    def lease(self) -> ExecutionLeaseView:
        ...
    @property
    def quarantined(self) -> bool:
        ...
    @property
    def last_evidence(self) -> str:
        ...
    @property
    def budget(self) -> DispatchBudgetView:
        "Absent when not set; use get()."
        ...


class SessionSnapshotView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def task_id(self) -> str | None:
        ...
    @property
    def provider(self) -> str:
        ...
    @property
    def model(self) -> str:
        ...
    @property
    def provider_session_id(self) -> str | None:
        ...
    @property
    def generation(self) -> int:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def status(self) -> Literal["idle", "running", "pausing", "paused", "closed", "outcome_unknown"]:
        ...
    @property
    def active_dispatch_id(self) -> str | None:
        ...
    @property
    def pause_origin(self) -> Literal["client", "runtime"]:
        "Durable origin of a control pause. Absent legacy pauses cannot be resumed by a runtime tool. Absent when not set; use get()."
        ...
    @property
    def execution(self) -> SessionExecutionView:
        "Absent when not set; use get()."
        ...
    @property
    def retry_identity(self) -> RetryIdentityView:
        "Absent when not set; use get()."
        ...
    @property
    def task_ids(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def root_task_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def permission_profile(self) -> Literal["read-only", "workspace-write"]:
        "Absent when not set; use get()."
        ...
    @property
    def write_paths(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def nativeCheckpoint(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def forkSource(self) -> Mapping[str, Any]:
        "Absent when not set; use get()."
        ...
    @property
    def generations(self) -> Sequence[Mapping[str, Any]]:
        "Absent when not set; use get()."
        ...
    @property
    def label(self) -> str:
        "The host's own filterable label, 1 to 256 UTF-8 bytes (SPEC-0027 L01). Absent when not set; use get()."
        ...
    @property
    def metadata(self) -> Mapping[str, Any]:
        "The host's own JSON object, at most 4096 bytes when encoded and 16 levels deep (SPEC-0027 L01). Absent when not set; use get()."
        ...


class SnapshotPageView(View, Protocol):
    @property
    def snapshot_id(self) -> str:
        ...
    @property
    def store_id(self) -> str:
        ...
    @property
    def cursor(self) -> str:
        ...
    @property
    def retention_floor_cursor(self) -> str:
        ...
    @property
    def expires_at(self) -> str:
        ...
    @property
    def items(self) -> Sequence[Mapping[str, Any]]:
        ...
    @property
    def next_offset(self) -> int:
        ...
    @property
    def done(self) -> bool:
        ...


class TaskBlockerView(View, Protocol):
    @property
    def reason(self) -> Literal["scheduler_failed", "host_stopping", "capacity", "quarantine_capacity", "resource_cleanup", "execution_conflict", "storage", "session_busy", "write_conflict", "scheduling", "dependency"]:
        ...
    @property
    def task_ids(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def session_id(self) -> str:
        "Absent when not set; use get()."
        ...


class TaskGetManyResultView(View, Protocol):
    @property
    def tasks(self) -> Sequence[TaskSnapshotView]:
        ...
    @property
    def missing(self) -> Sequence[str]:
        ...


class TaskListResultView(View, Protocol):
    @property
    def tasks(self) -> Sequence[TaskSnapshotView]:
        ...
    @property
    def next_cursor(self) -> str | None:
        ...


class TaskSnapshotPausedByCloseView(View, Protocol):
    @property
    def operation_id(self) -> str:
        ...
    @property
    def was_running(self) -> bool:
        ...


class TaskSnapshotRevisionRequestView(View, Protocol):
    @property
    def approval_id(self) -> str:
        ...
    @property
    def comment(self) -> str:
        ...


class TaskSnapshotView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def status(self) -> Literal["queued", "running", "waiting_approval", "paused", "blocked", "completed", "failed", "cancelled", "waiting_dependency", "verifying"]:
        ...
    @property
    def revision(self) -> int:
        ...
    @property
    def session_id(self) -> str:
        ...
    @property
    def spec(self) -> TaskSpecView:
        ...
    @property
    def artifact_refs(self) -> Sequence[str]:
        ...
    @property
    def result(self) -> str | None:
        ...
    @property
    def reason(self) -> str | None:
        ...
    @property
    def approval_id(self) -> str | None:
        ...
    @property
    def created_at(self) -> str:
        ...
    @property
    def updated_at(self) -> str:
        ...
    @property
    def retry_identity(self) -> RetryIdentityView:
        "Absent when not set; use get()."
        ...
    @property
    def root_task_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def write_paths(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def verification_rules(self) -> Sequence[Mapping[str, Any]]:
        "Absent when not set; use get()."
        ...
    @property
    def verification_attempts(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def routing(self) -> RoutingDecisionView:
        "Absent when not set; use get()."
        ...
    @property
    def kind(self) -> Literal["work", "compaction"]:
        "Absent when not set; use get()."
        ...
    @property
    def maintenanceOperationId(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def revision_request(self) -> TaskSnapshotRevisionRequestView:
        "Absent when not set; use get()."
        ...
    @property
    def dependency_results_delivered(self) -> bool:
        "Absent when not set; use get()."
        ...
    @property
    def blocked_by(self) -> TaskBlockerView:
        "Absent when not set; use get()."
        ...
    @property
    def delivered_at(self) -> str:
        "The time the task last delivered a result: its latest review for human acceptance, or its completion when its checks passed (SPEC-0029 B01). Absent when not set; use get()."
        ...
    @property
    def paused_by_close(self) -> TaskSnapshotPausedByCloseView:
        "Present while the task stays paused by a close; wasRunning says whether the close interrupted its turn (SPEC-0029 D01). Absent when not set; use get()."
        ...


class TaskSpecAcceptanceView(View, Protocol):
    @property
    def mode(self) -> Literal["human"]:
        ...
    @property
    def criteria(self) -> Sequence[str]:
        ...


class TaskSpecView(View, Protocol):
    @property
    def goal(self) -> str:
        ...
    @property
    def runtime(self) -> RuntimeSpecView:
        ...
    @property
    def acceptance(self) -> TaskSpecAcceptanceView:
        ...
    @property
    def dependency_task_ids(self) -> Sequence[str]:
        "Absent when not set; use get()."
        ...
    @property
    def parent_task_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def write_scope(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def context_plan(self) -> ContextPlanView:
        "Absent when not set; use get()."
        ...
    @property
    def budget(self) -> MoneyBudgetView:
        "Absent when not set; use get()."
        ...
    @property
    def context_estimate(self) -> Mapping[str, Any]:
        "Absent when not set; use get()."
        ...
    @property
    def write_path(self) -> str:
        "An existing workspace path inside writeScope; requires writeScope. Absent when not set; use get()."
        ...
    @property
    def label(self) -> str:
        "The host's own filterable label, 1 to 256 UTF-8 bytes (SPEC-0027 L01). Absent when not set; use get()."
        ...
    @property
    def metadata(self) -> Mapping[str, Any]:
        "The host's own JSON object, at most 4096 bytes when encoded and 16 levels deep (SPEC-0027 L01). Absent when not set; use get()."
        ...


class UsageByTaskResultView(View, Protocol):
    @property
    def tasks(self) -> Sequence[UsageTaskTotalsView]:
        ...
    @property
    def missing(self) -> Sequence[str]:
        ...


class UsageModelTotalsView(View, Protocol):
    @property
    def provider(self) -> str:
        ...
    @property
    def model(self) -> str | None:
        ...
    @property
    def records(self) -> int:
        ...
    @property
    def input_tokens(self) -> int:
        ...
    @property
    def cached_input_tokens(self) -> int:
        ...
    @property
    def cache_write_input_tokens(self) -> int:
        ...
    @property
    def cache_write_5m_input_tokens(self) -> int:
        ...
    @property
    def cache_write_1h_input_tokens(self) -> int:
        ...
    @property
    def output_tokens(self) -> int:
        ...
    @property
    def unknown_records(self) -> int:
        ...


class UsageRecordView(View, Protocol):
    @property
    def id(self) -> str:
        ...
    @property
    def task_id(self) -> str:
        ...
    @property
    def dispatch_id(self) -> str:
        ...
    @property
    def provider(self) -> str:
        ...
    @property
    def input_tokens(self) -> int | None:
        ...
    @property
    def cached_input_tokens(self) -> int | None:
        ...
    @property
    def cache_write_input_tokens(self) -> int | None:
        ...
    @property
    def cache_write_5m_input_tokens(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def cache_write_1h_input_tokens(self) -> int:
        "Absent when not set; use get()."
        ...
    @property
    def output_tokens(self) -> int | None:
        ...
    @property
    def raw(self) -> Any:
        ...
    @property
    def session_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def model(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def root_task_id(self) -> str:
        "Absent when not set; use get()."
        ...
    @property
    def recorded_at(self) -> str:
        "Absent when not set; use get()."
        ...


class UsageSummaryView(View, Protocol):
    @property
    def root_task_id(self) -> str:
        ...
    @property
    def by_model(self) -> Sequence[UsageModelTotalsView]:
        ...
    @property
    def totals(self) -> UsageTotalsView:
        ...
    @property
    def completeness(self) -> Literal["reported", "unknown"]:
        ...


class UsageTaskTotalsView(View, Protocol):
    @property
    def task_id(self) -> str:
        ...
    @property
    def by_model(self) -> Sequence[UsageModelTotalsView]:
        ...
    @property
    def totals(self) -> UsageTotalsView:
        ...
    @property
    def completeness(self) -> Literal["reported", "unknown"]:
        ...


class UsageTotalsView(View, Protocol):
    @property
    def records(self) -> int:
        ...
    @property
    def input_tokens(self) -> int:
        ...
    @property
    def cached_input_tokens(self) -> int:
        ...
    @property
    def cache_write_input_tokens(self) -> int:
        ...
    @property
    def cache_write_5m_input_tokens(self) -> int:
        ...
    @property
    def cache_write_1h_input_tokens(self) -> int:
        ...
    @property
    def output_tokens(self) -> int:
        ...
    @property
    def unknown_records(self) -> int:
        ...


class WorkflowCapabilityView(View, Protocol):
    @property
    def version(self) -> Literal[1]:
        ...
    @property
    def dependency_results(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def revise(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def delegation_approval(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def handoffs(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def write_path(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def runtime_rules(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def task_list(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def context_check(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def labels(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def task_queries(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def queue_reasons(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def pause_close(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def rule_retirement(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...
    @property
    def usage_by_task(self) -> Literal[true]:
        "Absent when not set; use get()."
        ...


class MessageReceiptView(MessageSnapshotView, ReceiptView, Protocol):
    """MessageSnapshotView as a mutation returns it, with its receipt."""


class OperationReceiptView(OperationSnapshotView, ReceiptView, Protocol):
    """OperationSnapshotView as a mutation returns it, with its receipt."""


class SessionReceiptView(SessionSnapshotView, ReceiptView, Protocol):
    """SessionSnapshotView as a mutation returns it, with its receipt."""


class TaskReceiptView(TaskSnapshotView, ReceiptView, Protocol):
    """TaskSnapshotView as a mutation returns it, with its receipt."""


# Each view's fields as Python names them, and whether the schema requires them.
FIELDS: dict[str, dict[str, bool]] = {
    "ApprovalRequestTargetView": {"artifact_refs": True, "dispatch_id": False, "generation": False, "permission": False, "provider_session_id": False, "provider_turn_id": False, "request_digest": False, "request_id": False, "session_id": False, "task_id": True, "task_revision": True, "tool_name": False},
    "ApprovalRequestView": {"approval_id": True, "comment": False, "evidence_refs": True, "expires_at": True, "purpose": True, "revision": True, "status": True, "summary": True, "target": True, "task_id": True},
    "ContextPlanView": {"candidate_session_id": False, "context_refs": False, "dependency_task_ids": False, "fallback_modes": False, "independent": True, "max_queue_wait_ms": False, "requested_mode": True, "snapshot_ref": False},
    "DispatchBudgetView": {"acceptance_deadline_at": True, "acceptance_source": True, "deadline_at": True, "effective_acceptance_ms": True, "effective_turn_ms": True, "entered_at": True, "policy_version": True, "turn_source": True},
    "ExecutionConflictResolutionView": {"evidence_ref": True, "occurred_at": True, "operation_id": True},
    "ExecutionConflictView": {"conflicting_evidence_ref": True, "created_at": True, "dispatch_id": True, "generation": True, "id": True, "release_evidence_ref": True, "resolution": False, "revision": True, "session_id": True, "status": True, "task_id": True},
    "ExecutionLeaseView": {"acquired_at": True, "release_evidence_ref": False, "release_reason": False, "released_at": False, "status": True, "version": True},
    "HandoffListResultView": {"handoffs": True, "next_cursor": True},
    "HandoffRequestView": {"comment": False, "context_refs": True, "created_at": True, "expires_at": True, "from_dispatch_id": True, "from_generation": True, "from_session_id": True, "from_task_id": True, "goal": True, "handoff_id": True, "resolved_at": False, "revision": True, "root_task_id": True, "status": True, "target_session_id": True, "task_id": False},
    "InitializeResultCapabilitiesStoreNamespacesView": {"digest_version": False, "expected_store_id": False, "version": True},
    "InitializeResultCapabilitiesView": {"readOnly": False, "store_namespaces": True, "workflow": False},
    "InitializeResultView": {"capabilities": True, "engine_version": True, "instance_id": True, "protocol_version": True, "schema_version": True, "store_id": True},
    "MessageReceiptView": {"artifact_refs": False, "created_at": False, "expected_generation": True, "expires_at": False, "from_session_id": True, "hop_count": False, "id": True, "idempotency_key": True, "kind": True, "method": True, "reply_to_message_id": False, "retry_identity": True, "scope": True, "status": True, "summary": True, "task_id": True, "to_session_id": True, "ttl_ms": False},
    "MessageSnapshotView": {"artifact_refs": False, "created_at": False, "expected_generation": True, "expires_at": False, "from_session_id": True, "hop_count": False, "id": True, "idempotency_key": True, "kind": True, "reply_to_message_id": False, "retry_identity": False, "status": True, "summary": True, "task_id": True, "to_session_id": True, "ttl_ms": False},
    "MoneyBudgetView": {"currency": True, "max_cost": True, "reserve_per_dispatch": True},
    "OperationLifecycleView": {"deadline_at": True, "entered_at": True, "expected_dispatch_id": True, "expected_generation": True, "expired_at": False, "kind": True, "last_evidence": True, "may_have_been_sent": True, "policy_version": True},
    "OperationReceiptView": {"error": True, "id": True, "idempotency_key": True, "lifecycle": False, "method": True, "resolution": False, "result": True, "retry_identity": True, "scope": True, "status": True, "target_id": True},
    "OperationSnapshotErrorView": {"code": True, "message": True},
    "OperationSnapshotResolutionView": {"occurred_at": True, "operation_id": True, "outcome": True},
    "OperationSnapshotView": {"error": True, "id": True, "idempotency_key": True, "lifecycle": False, "method": True, "resolution": False, "result": True, "retry_identity": False, "scope": True, "status": True, "target_id": True},
    "RegisteredVerificationRuleView": {"argv": True, "baseline_paths": False, "cwd_relative": True, "digest": True, "id": True, "max_output_bytes": False, "permission_profile": True, "retired_at": False, "source": True, "success": True, "timeout_ms": True, "version": True},
    "RetryIdentityView": {"digest_version": True, "idempotency_key": True, "method": True, "request_digest": True, "scope": True, "store_id": True},
    "RoutingDecisionView": {"candidate_session_id": True, "deadline_at": True, "enqueued_at": True, "expected_generation": True, "expired_at": False, "fallback_modes": True, "max_queue_wait_ms": True, "mode": True, "policy_version": True, "reason_code": True, "submitted_at": False},
    "RuleListResultView": {"rules": True},
    "RuntimeInspectionView": {"detail": True, "execution": True, "provider_session_id": True, "records": True, "status": True, "target": False, "truncated": True},
    "RuntimeSpecView": {"model": True, "provider": True},
    "SchedulerSnapshotConflictsView": {"conflict_id": True, "dispatch_id": True, "revision": True},
    "SchedulerSnapshotOccupantsView": {"dispatch_id": True, "entered_at": True, "last_evidence": True, "lease_status": True, "quarantined": True, "session_id": True, "task_id": True},
    "SchedulerSnapshotView": {"can_dispatch": True, "conflicts": True, "conflicts_truncated": True, "execution_occupied": True, "max_active_sessions": True, "max_quarantined_dispatches": True, "occupants": True, "open_conflicts": True, "quarantine_reserved": True, "quarantined": True, "reasons": True, "truncated": True},
    "SessionExecutionView": {"budget": False, "dispatch_id": True, "last_evidence": True, "lease": True, "quarantined": True},
    "SessionReceiptView": {"active_dispatch_id": True, "execution": False, "forkSource": False, "generation": True, "generations": False, "id": True, "idempotency_key": True, "label": False, "metadata": False, "method": True, "model": True, "nativeCheckpoint": False, "pause_origin": False, "permission_profile": False, "provider": True, "provider_session_id": True, "retry_identity": True, "revision": True, "root_task_id": False, "scope": True, "status": True, "task_id": True, "task_ids": False, "write_paths": False},
    "SessionSnapshotView": {"active_dispatch_id": True, "execution": False, "forkSource": False, "generation": True, "generations": False, "id": True, "label": False, "metadata": False, "model": True, "nativeCheckpoint": False, "pause_origin": False, "permission_profile": False, "provider": True, "provider_session_id": True, "retry_identity": False, "revision": True, "root_task_id": False, "status": True, "task_id": True, "task_ids": False, "write_paths": False},
    "SnapshotPageView": {"cursor": True, "done": True, "expires_at": True, "items": True, "next_offset": True, "retention_floor_cursor": True, "snapshot_id": True, "store_id": True},
    "TaskBlockerView": {"reason": True, "session_id": False, "task_ids": False},
    "TaskGetManyResultView": {"missing": True, "tasks": True},
    "TaskListResultView": {"next_cursor": True, "tasks": True},
    "TaskReceiptView": {"approval_id": True, "artifact_refs": True, "blocked_by": False, "created_at": True, "delivered_at": False, "dependency_results_delivered": False, "id": True, "idempotency_key": True, "kind": False, "maintenanceOperationId": False, "method": True, "paused_by_close": False, "reason": True, "result": True, "retry_identity": True, "revision": True, "revision_request": False, "root_task_id": False, "routing": False, "scope": True, "session_id": True, "spec": True, "status": True, "updated_at": True, "verification_attempts": False, "verification_rules": False, "write_paths": False},
    "TaskSnapshotPausedByCloseView": {"operation_id": True, "was_running": True},
    "TaskSnapshotRevisionRequestView": {"approval_id": True, "comment": True},
    "TaskSnapshotView": {"approval_id": True, "artifact_refs": True, "blocked_by": False, "created_at": True, "delivered_at": False, "dependency_results_delivered": False, "id": True, "kind": False, "maintenanceOperationId": False, "paused_by_close": False, "reason": True, "result": True, "retry_identity": False, "revision": True, "revision_request": False, "root_task_id": False, "routing": False, "session_id": True, "spec": True, "status": True, "updated_at": True, "verification_attempts": False, "verification_rules": False, "write_paths": False},
    "TaskSpecAcceptanceView": {"criteria": True, "mode": True},
    "TaskSpecView": {"acceptance": True, "budget": False, "context_estimate": False, "context_plan": False, "dependency_task_ids": False, "goal": True, "label": False, "metadata": False, "parent_task_id": False, "runtime": True, "write_path": False, "write_scope": False},
    "UsageByTaskResultView": {"missing": True, "tasks": True},
    "UsageModelTotalsView": {"cache_write_1h_input_tokens": True, "cache_write_5m_input_tokens": True, "cache_write_input_tokens": True, "cached_input_tokens": True, "input_tokens": True, "model": True, "output_tokens": True, "provider": True, "records": True, "unknown_records": True},
    "UsageRecordView": {"cache_write_1h_input_tokens": False, "cache_write_5m_input_tokens": False, "cache_write_input_tokens": True, "cached_input_tokens": True, "dispatch_id": True, "id": True, "input_tokens": True, "model": False, "output_tokens": True, "provider": True, "raw": True, "recorded_at": False, "root_task_id": False, "session_id": False, "task_id": True},
    "UsageSummaryView": {"by_model": True, "completeness": True, "root_task_id": True, "totals": True},
    "UsageTaskTotalsView": {"by_model": True, "completeness": True, "task_id": True, "totals": True},
    "UsageTotalsView": {"cache_write_1h_input_tokens": True, "cache_write_5m_input_tokens": True, "cache_write_input_tokens": True, "cached_input_tokens": True, "input_tokens": True, "output_tokens": True, "records": True, "unknown_records": True},
    "WorkflowCapabilityView": {"context_check": False, "delegation_approval": False, "dependency_results": False, "handoffs": False, "labels": False, "pause_close": False, "queue_reasons": False, "revise": False, "rule_retirement": False, "runtime_rules": False, "task_list": False, "task_queries": False, "usage_by_task": False, "version": True, "write_path": False},
}
# The fields that hold nested views.
NESTED: dict[str, dict[str, str]] = {
    "ApprovalRequestView": {"target": "ApprovalRequestTargetView"},
    "ExecutionConflictView": {"resolution": "ExecutionConflictResolutionView"},
    "HandoffListResultView": {"handoffs": "HandoffRequestView"},
    "InitializeResultCapabilitiesView": {"store_namespaces": "InitializeResultCapabilitiesStoreNamespacesView", "workflow": "WorkflowCapabilityView"},
    "InitializeResultView": {"capabilities": "InitializeResultCapabilitiesView"},
    "MessageReceiptView": {"retry_identity": "RetryIdentityView"},
    "MessageSnapshotView": {"retry_identity": "RetryIdentityView"},
    "OperationReceiptView": {"error": "OperationSnapshotErrorView", "lifecycle": "OperationLifecycleView", "resolution": "OperationSnapshotResolutionView", "retry_identity": "RetryIdentityView"},
    "OperationSnapshotView": {"error": "OperationSnapshotErrorView", "lifecycle": "OperationLifecycleView", "resolution": "OperationSnapshotResolutionView", "retry_identity": "RetryIdentityView"},
    "RuleListResultView": {"rules": "RegisteredVerificationRuleView"},
    "SchedulerSnapshotView": {"conflicts": "SchedulerSnapshotConflictsView", "occupants": "SchedulerSnapshotOccupantsView"},
    "SessionExecutionView": {"budget": "DispatchBudgetView", "lease": "ExecutionLeaseView"},
    "SessionReceiptView": {"execution": "SessionExecutionView", "retry_identity": "RetryIdentityView"},
    "SessionSnapshotView": {"execution": "SessionExecutionView", "retry_identity": "RetryIdentityView"},
    "TaskGetManyResultView": {"tasks": "TaskSnapshotView"},
    "TaskListResultView": {"tasks": "TaskSnapshotView"},
    "TaskReceiptView": {"blocked_by": "TaskBlockerView", "paused_by_close": "TaskSnapshotPausedByCloseView", "retry_identity": "RetryIdentityView", "revision_request": "TaskSnapshotRevisionRequestView", "routing": "RoutingDecisionView", "spec": "TaskSpecView"},
    "TaskSnapshotView": {"blocked_by": "TaskBlockerView", "paused_by_close": "TaskSnapshotPausedByCloseView", "retry_identity": "RetryIdentityView", "revision_request": "TaskSnapshotRevisionRequestView", "routing": "RoutingDecisionView", "spec": "TaskSpecView"},
    "TaskSpecView": {"acceptance": "TaskSpecAcceptanceView", "budget": "MoneyBudgetView", "context_plan": "ContextPlanView", "runtime": "RuntimeSpecView"},
    "UsageByTaskResultView": {"tasks": "UsageTaskTotalsView"},
    "UsageSummaryView": {"by_model": "UsageModelTotalsView", "totals": "UsageTotalsView"},
    "UsageTaskTotalsView": {"by_model": "UsageModelTotalsView", "totals": "UsageTotalsView"},
}
# Views whose results may hold further fields, read with view["name"].
OPEN: frozenset[str] = frozenset(["ApprovalRequestTargetView", "ApprovalRequestView", "DispatchBudgetView", "ExecutionConflictResolutionView", "ExecutionConflictView", "ExecutionLeaseView", "InitializeResultCapabilitiesStoreNamespacesView", "InitializeResultCapabilitiesView", "InitializeResultView", "MessageSnapshotView", "OperationLifecycleView", "OperationSnapshotErrorView", "OperationSnapshotResolutionView", "OperationSnapshotView", "RuntimeInspectionView", "SchedulerSnapshotConflictsView", "SchedulerSnapshotOccupantsView", "SchedulerSnapshotView", "SessionExecutionView", "SessionSnapshotView", "TaskSnapshotView", "UsageRecordView", "WorkflowCapabilityView"])
